✨ new(presets): Add pro tag in inactive features.
wpmudev/shared-modules pull request #136
Opened 2022-05-24 06:01 UTC by creador-dev

2022-05-24 12:32 UTC, iamleigh requested changes

2022-05-24 12:32 UTC, iamleigh commented on packages/shared-presets/lib/shared-presets.js
> +								<div key={ name } name={ lang.settingsLabels[ name ] } status={ item.config.strings[ name ] } protag={ item.config.strings[ name ] } />
@creador-dev, you're getting the "name" string to set the "pro" tag status when it should be boolean. Also, keep in mind the "pro" variable doesn't exist in the API, but we're adding it after the release, so you should make sure it appears when the value is set to "true".

2022-05-24 13:54 UTC, creador-dev commented on packages/shared-presets/lib/components/table.js
> +				.sui-tag-pro{
@iamleigh this CSS was written for the sub-options.
<img width="875" alt="Screenshot 2022-05-24 at 7 22 15 PM" src="https://user-images.githubusercontent.com/40248406/170052651-415d8e28-4097-4f1c-be8f-9f44ed41b6d8.png">

2023-01-18 05:22 UTC, iamleigh approved these changes

2023-01-18 05:27 UTC, merged